site_name: MCP BigQuery Documentation
site_description: MCP server for BigQuery SQL validation and dry-run analysis
site_author: MCP BigQuery Contributors
site_url: https://caron14.github.io/mcp-bigquery/
repo_url: https://github.com/caron14/mcp-bigquery
repo_name: caron14/mcp-bigquery
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/caron14/mcp-bigquery
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mcp-bigquery/

nav:
  - Home: index.md
  - Getting Started:
    - get-started/index.md
    - Installation: get-started/installation.md
    - Quick Start: get-started/quickstart.md
    - Authentication: get-started/authentication.md
  - Guides:
    - guides/index.md
    - SQL Validation: guides/validation.md
    - Dry-Run Analysis: guides/dry-run.md
    - Cost Estimation: guides/cost-estimation.md
    - Using Parameters: guides/parameters.md
  - API Reference:
    - api-reference/index.md
    - Tools: api-reference/tools.md
    - Response Schemas: api-reference/schemas.md
    - Error Reference: api-reference/errors.md
  - Deployment:
    - deploy/index.md
    - Claude Code Setup: deploy/claude-code.md
    - Other MCP Clients: deploy/mcp-clients.md
  - Examples:
    - examples/index.md
    - Basic Usage: examples/basic.md
    - Advanced Scenarios: examples/advanced.md
  - Development:
    - development/index.md
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md